//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Inputs/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""185fe18e-67b0-4ac8-8dcd-7d567cad6a29"",
            ""actions"": [
                {
                    ""name"": ""PlayerExtremity1"",
                    ""type"": ""Value"",
                    ""id"": ""d4ea13b2-7267-4f43-a0ab-7df07da540f1"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayerExtremity2"",
                    ""type"": ""Value"",
                    ""id"": ""abc234b1-a599-48df-a4e4-bf1a378e736e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayerMap1"",
                    ""type"": ""Value"",
                    ""id"": ""c95a3e67-8604-458a-b781-c2a40ac12f76"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PlayerMap2"",
                    ""type"": ""Value"",
                    ""id"": ""d9bb240c-9ac0-47e3-9cae-3fb29d310a16"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""6479875d-b82b-4f9c-89b6-0f7f436256e1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMap1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b6993f0f-425a-4fa4-af1e-45ca662ce405"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMap1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""54fa86a0-7e4d-4826-8b71-232013099287"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMap1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dd5e31cf-bd6c-4d48-ac48-79557d13b211"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMap1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bd5270a7-f4a0-4351-96bc-061375d6e372"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMap1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ea13dca7-2169-43d9-8575-0ef6e4d8b816"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMap2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4f1878fc-cee3-47d9-ab8f-d16a0c1a34b3"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMap2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""79938438-ccfa-440c-a6f9-2b49cf259335"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMap2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bb9f49e2-3ca8-4b3d-b441-551324e81532"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMap2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c9cebeb7-117f-455f-8daa-9f9b5976283a"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerMap2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""a58f1ea6-440f-416d-bc60-df1d6a8d91f0"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerExtremity1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""67f1883c-2f16-402b-8b1e-0ca50215f6ad"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerExtremity1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""57caf70f-54e9-4b0b-b956-2ed06b883cfc"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerExtremity1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""59ccd1c7-6280-4e12-807f-989351003ef7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerExtremity2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""558203f0-c708-4eec-9c1c-fcb9d5c2d93e"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerExtremity2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cc8e6395-bd78-48a4-ba9c-3356ccdafd37"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayerExtremity2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_PlayerExtremity1 = m_Player.FindAction("PlayerExtremity1", throwIfNotFound: true);
        m_Player_PlayerExtremity2 = m_Player.FindAction("PlayerExtremity2", throwIfNotFound: true);
        m_Player_PlayerMap1 = m_Player.FindAction("PlayerMap1", throwIfNotFound: true);
        m_Player_PlayerMap2 = m_Player.FindAction("PlayerMap2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_PlayerExtremity1;
    private readonly InputAction m_Player_PlayerExtremity2;
    private readonly InputAction m_Player_PlayerMap1;
    private readonly InputAction m_Player_PlayerMap2;
    public struct PlayerActions
    {
        private @Inputs m_Wrapper;
        public PlayerActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlayerExtremity1 => m_Wrapper.m_Player_PlayerExtremity1;
        public InputAction @PlayerExtremity2 => m_Wrapper.m_Player_PlayerExtremity2;
        public InputAction @PlayerMap1 => m_Wrapper.m_Player_PlayerMap1;
        public InputAction @PlayerMap2 => m_Wrapper.m_Player_PlayerMap2;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @PlayerExtremity1.started += instance.OnPlayerExtremity1;
            @PlayerExtremity1.performed += instance.OnPlayerExtremity1;
            @PlayerExtremity1.canceled += instance.OnPlayerExtremity1;
            @PlayerExtremity2.started += instance.OnPlayerExtremity2;
            @PlayerExtremity2.performed += instance.OnPlayerExtremity2;
            @PlayerExtremity2.canceled += instance.OnPlayerExtremity2;
            @PlayerMap1.started += instance.OnPlayerMap1;
            @PlayerMap1.performed += instance.OnPlayerMap1;
            @PlayerMap1.canceled += instance.OnPlayerMap1;
            @PlayerMap2.started += instance.OnPlayerMap2;
            @PlayerMap2.performed += instance.OnPlayerMap2;
            @PlayerMap2.canceled += instance.OnPlayerMap2;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @PlayerExtremity1.started -= instance.OnPlayerExtremity1;
            @PlayerExtremity1.performed -= instance.OnPlayerExtremity1;
            @PlayerExtremity1.canceled -= instance.OnPlayerExtremity1;
            @PlayerExtremity2.started -= instance.OnPlayerExtremity2;
            @PlayerExtremity2.performed -= instance.OnPlayerExtremity2;
            @PlayerExtremity2.canceled -= instance.OnPlayerExtremity2;
            @PlayerMap1.started -= instance.OnPlayerMap1;
            @PlayerMap1.performed -= instance.OnPlayerMap1;
            @PlayerMap1.canceled -= instance.OnPlayerMap1;
            @PlayerMap2.started -= instance.OnPlayerMap2;
            @PlayerMap2.performed -= instance.OnPlayerMap2;
            @PlayerMap2.canceled -= instance.OnPlayerMap2;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnPlayerExtremity1(InputAction.CallbackContext context);
        void OnPlayerExtremity2(InputAction.CallbackContext context);
        void OnPlayerMap1(InputAction.CallbackContext context);
        void OnPlayerMap2(InputAction.CallbackContext context);
    }
}
